Final changes for Elasticsearch 5.x

diff --git a/clique-base/Dockerfile b/clique-base/Dockerfile
--- a/clique-base/Dockerfile
+++ b/clique-base/Dockerfile
@@ -1,64 +1,107 @@
-FROM ubuntu:15.10
+FROM ubuntu:16.04
 
 # Elasticsearch and Kibana
 
-ENV ELASTICSEARCH_MAJOR 2.4
-ENV ELASTICSEARCH_VERSION 2.4.4
-ENV ELASTICSEARCH_REPO_BASE http://packages.elasticsearch.org/elasticsearch/2.x/debian
-
-ENV KIBANA_VERSION 4.6.4
-
 RUN set -ex && \
-    locale-gen en_US.UTF-8 && \
+    \
     groupadd -r elasticsearch && useradd -r -m -g elasticsearch elasticsearch && \
     groupadd -r kibana && useradd -r -m -g kibana kibana && \
-		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && \
-    arch="$(dpkg --print-architecture)" && \
-	  apt-get update && \
-    apt-get install -y curl && \
-    curl -o /usr/local/bin/gosu -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-$arch" && \
-	  curl -o /usr/local/bin/gosu.asc -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-$arch.asc" && \
-	  gpg --verify /usr/local/bin/gosu.asc && \
-	  rm /usr/local/bin/gosu.asc && \
-	  chmod +x /usr/local/bin/gosu && \
-		apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 && \
-    echo "deb $ELASTICSEARCH_REPO_BASE stable main" > /etc/apt/sources.list.d/elasticsearch.list && \
-	  apt-get update && \
-	  apt-get install -y wget supervisor openjdk-8-jre unzip && \
-		apt-get install -y --no-install-recommends elasticsearch=$ELASTICSEARCH_VERSION && \
-	  for path in \
-		  /usr/share/elasticsearch/data \
-		  /usr/share/elasticsearch/logs \
-		  /usr/share/elasticsearch/config \
-		  /usr/share/elasticsearch/config/scripts \
-	  ; do \
-		  mkdir -p "$path"; \
-		  chown -R elasticsearch:elasticsearch "$path"; \
-	  done && \
-		curl -fSL "https://download.elastic.co/kibana/kibana/kibana-${KIBANA_VERSION}-linux-x86_64.tar.gz" -o kibana.tar.gz && \
-	  mkdir -p /usr/share/kibana && \
-	  tar -xz --strip-components=1 -C /usr/share/kibana -f kibana.tar.gz && \
-	  chown -R kibana:kibana /usr/share/kibana && \
-	  rm kibana.tar.gz && \
-	  /usr/share/kibana/bin/kibana plugin --install elastic/sense && \
-	  chown -R elasticsearch:elasticsearch /usr/share/elasticsearch && \
-	  chown -R kibana:kibana /usr/share/kibana && \
-	  mkdir -p /usr/local/vamp && \
-	  apt-get purge -y gcc make && \
-	  apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
+    \
+    apt-get update && apt-get install -y wget supervisor openjdk-8-jre unzip
+
+# grab gosu for easy step-down from root
+ENV GOSU_VERSION 1.10
+RUN set -x \
+	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
+	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
+	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
+	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
+	&& chmod +x /usr/local/bin/gosu \
+	&& gosu nobody true
+
+# KEYS
+
+RUN set -ex; \
+# https://artifacts.elastic.co/GPG-KEY-elasticsearch
+	key='46095ACC8548582C1A2699A9D27D666CD88E42B4'; \
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+	gpg --export "$key" > /etc/apt/trusted.gpg.d/elastic.gpg; \
+	rm -rf "$GNUPGHOME"; \
+	apt-key list
+
+# ELASTICSEACH
+RUN set -x \
+	&& apt-get update && apt-get install -y --no-install-recommends apt-transport-https && rm -rf /var/lib/apt/lists/* \
+	&& echo 'deb https://artifacts.elastic.co/packages/5.x/apt stable main' > /etc/apt/sources.list.d/elasticsearch.list
+
+ENV ELASTICSEARCH_VERSION 5.5.2
+ENV ELASTICSEARCH_DEB_VERSION 5.5.2
+
+RUN set -x \
+	\
+# don't allow the package to install its sysctl file (causes the install to fail)
+# Failed to write '262144' to '/proc/sys/vm/max_map_count': Read-only file system
+	&& dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf \
+	\
+	&& apt-get update \
+	&& apt-get install -y --no-install-recommends "elasticsearch=$ELASTICSEARCH_DEB_VERSION" \
+	&& rm -rf /var/lib/apt/lists/*
+
+ENV PATH /usr/share/elasticsearch/bin:$PATH
+
+
+RUN for path in \
+    		  /usr/share/elasticsearch/data \
+    		  /usr/share/elasticsearch/logs \
+    		  /usr/share/elasticsearch/config \
+    		  /usr/share/elasticsearch/config/scripts \
+    	  ; do \
+    		  mkdir -p "$path"; \
+    		  chown -R elasticsearch:elasticsearch "$path"; \
+    done && \
+    chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
+
 
 ENV LANG en_US.UTF-8
 ENV LANGUAGE en_US:en
 ENV LC_ALL en_US.UTF-8
 
-ENV PATH /usr/share/elasticsearch/bin:/usr/share/kibana/bin:$PATH
+#  Kibana
+# https://www.elastic.co/guide/en/kibana/5.0/deb.html
+#RUN echo 'deb https://artifacts.elastic.co/packages/5.x/apt stable main' > /etc/apt/sources.list.d/kibana.list
 
-ADD elasticsearch/elasticsearch.yml elasticsearch/logging.yml /usr/share/elasticsearch/config/
-ADD kibana/kibana.yml /usr/share/kibana/config/kibana.yml
-ADD kibana/start.sh /usr/share/kibana/bin/kibana-start
+ENV KIBANA_VERSION 5.5.2
+
+RUN set -x \
+	&& apt-get update \
+	&& apt-get install -y --no-install-recommends kibana=$KIBANA_VERSION \
+	&& rm -rf /var/lib/apt/lists/* \
+	\
+# the default "server.host" is "localhost" in 5+
+	&& sed -ri "s!^(\#\s*)?(server\.host:).*!\2 '0.0.0.0'!" /etc/kibana/kibana.yml \
+	&& grep -q "^server\.host: '0.0.0.0'\$" /etc/kibana/kibana.yml \
+	\
+# ensure the default configuration is useful when using --link
+	&& sed -ri "s!^(\#\s*)?(elasticsearch\.url:).*!\2 'http://elasticsearch:9200'!" /etc/kibana/kibana.yml \
+	&& grep -q "^elasticsearch\.url: 'http://elasticsearch:9200'\$" /etc/kibana/kibana.yml
+
+ENV PATH /usr/share/kibana/bin:$PATH
+
+
+
+COPY elasticsearch/config/elasticsearch.yml elasticsearch/log4j2.properties /usr/share/elasticsearch/
+COPY kibana/kibana.yml /usr/share/kibana/config/kibana.yml
+COPY kibana/start.sh /usr/share/kibana/bin/kibana-start
+# setup Supervisord
+COPY supervisord.conf /etc/supervisor/supervisord.conf
+
+
 
 EXPOSE 9200 9300
 EXPOSE 5601
 
-ADD supervisord.conf /etc/supervisor/supervisord.conf
+
 CMD ["supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
